### ISSUE TITLE
Snapdrop

### ISSUE THREAD

**Issue by Jona-than-XD** [tanujnotes/Snapdrop#2]
good morning please i am a student and i was trying to use your source code for a learning activity 

and its giving me errors while trying to use it with android studio 

which software is recommended to use for the source code

**Comment by tanujnotes** [comment]
Android Studio is what I use. What's the error you're seeing?

**Comment by Jona-than-XD** [comment]
Thank you sir it has been resolved a component of my android studio was outdated that's was why I got errors

**Comment by Jona-than-XD** [comment]
And sir I made the App just like yours with another site it's not able to download anything what should I do sir and have watched numerous tutorial online non was able to help

**Comment by tanujnotes** [comment]
Take a look at the JavascriptInterface file in the source code. That's where downloading happens.

**Comment by Jona-than-XD** [comment]
Okay sir thanks so much
