### ISSUE TITLE
Future of this project?

### ISSUE THREAD

**Issue by fm-sys** [tanujnotes/Snapdrop#3]
Hi @tanujnotes,

I have a similar but more advanced open source project already running a bit longer since October last year (but added to the [playstore](https://play.google.com/store/apps/details?id=com.fmsys.snapdrop) some months later). 
See https://github.com/fm-sys/snapdrop-android

This is also the android app, which is listed in the official Snapdrop FAQ.
https://github.com/RobinLinus/snapdrop/blob/master/docs/faq.md#third-party-apps

From time to time, I receive bug reports from your app in my repository. 
e.g. https://github.com/fm-sys/snapdrop-android/issues/72

Furthermore, there are is quite some activity (bug reports and PR's) happening in my repo and the [issues listed in your README](https://github.com/tanujnotes/Snapdrop#known-issues) are solved/not happening in my app. E.g. I don't use an explicit MIME type mapping, like it is done in your app. 

As this repo doesn't seem to be much maintained, so I would like to kindly ask you if you would be willing to take your "Snapdrop | Share it" out of the playstore? 

Please don't get me wrong, I don't want to destroy your work. However, the fact that two apps exist for one and the same use case is kind of confusing for users. 

I think it would be much easier, if we cooperate (if you still have time for this project at all?) in development. You are welcome to contribute to my repo if you find time!  ;-)

Please let me know what you think about my idea.

With kind regards
Florian

**Comment by tanujnotes** [comment]
No, thanks.

**Comment by xundeenergie** [comment]
In the other app i can configure my own pairdrop host.
In this app not.

So i choosed the other app.

That was easy.
