### ISSUE TITLE
Discovery doesn't work while Google Fi VPN is enabled

### ISSUE THREAD

**Issue by cnuss** [tanujnotes/Snapdrop#5]
Greetings!

Thanks for making the wonderful Snapdrop Android app. I believe this is the right repository, looks like there's a few Android flavors of this, but I found this from the Github link in the app.

I've attached a screen recording of the issue: 
https://user-images.githubusercontent.com/819991/135183093-7ade4279-d9ca-45f0-b430-a4213f66fd1b.mov

I have a Pixel 4, on Google Fi, with the VPN enabled, and a MacBook Pro 13 Big Sur.

Steps to recreate the issue: 

1) Ensure Google Fi VPN is enabled
1) Open Snapdrop.net or Chrome App
1) Open Snapdrop Android App
1) No devices show up on either side
1) Kill apps on macbook and android
1) Disable VPN on Google Fi
1) Open Apps
1) Devices nearby are discovered

Let me know if you need more information!

**Comment by tanujnotes** [comment]
Snapdrop website doesn't work with VPN enabled and that's why app doesn't work either. More info here: https://github.com/RobinLinus/snapdrop/issues/251

**Comment by cnuss** [comment]
Is it possible to add an alert that a VPN is enabled and functionality won't work? Could help for great UX

https://stackoverflow.com/questions/28386553/check-if-a-vpn-connection-is-active-in-android

**Comment by tanujnotes** [comment]
I'll see what I can do.
